application: gist-it-birdslikewires
version: 1

runtime: python27
api_version: 1
threadsafe: false

handlers:
  - url: /assets
    static_dir: assets
    expiration: 1d

  - url: .*
    script: app.py
